version: "3.3"

services:

  #--------------------------------------------
  postgres:
    container_name: ${PG_CTR_NAME}
    image: ${PG_IMAGE}
    profiles: ["base", "dbadmin"]
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ${PG_VOL_1}
      - ${PG_VOL_2}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      timeout: 15s
      interval: 5s
      retries: 100
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}

  #--------------------------------------------
  keycloak:
    container_name: ${KC_CTR_NAME}
    image: ${KC_IMAGE}
    profiles: ["base", "dbadmin"]
    ports:
      # https
      - "${KC_PORT}:8443"
      - "${KC_PORT_MGMT}:9000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${KC_VOL_1}
      - ${KC_VOL_2}
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PWD}
      KC_HEALTH_ENABLED: ${KC_HEALTH}
      KC_DB: ${DB_TYPE}
      KC_DB_URL: ${DB_URL}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PWD}
      KC_DB_SCHEMA: ${DB_SCHEMA}

    command:
      - ${KC_CMD_1}
      - ${KC_CMD_2}
      - ${KC_CMD_3} 
      - ${KC_CMD_4}
      - ${KC_CMD_5}

  #--------------------------------------------
  pgadmin:
    container_name: ${PA_CTR_NAME}
    image: ${PA_IMAGE}
    profiles: ["dbadmin"]
    ports:
      - ${PA_PORT}:80
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${PA_VOL_1}
      - ${PA_VOL_2}
    entrypoint: /bin/sh -c "${PA_SHELL_CMD}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PA_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PA_PWD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      GUNICORN_ACCESS_LOGFILE: "/dev/null"
