version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.19
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:Z
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "kogito", "-U", "kogito-user"]
      timeout: 15s
      interval: 5s
      retries: 100
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      # https
      - "8443:8443"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./realms/quarkus-realm.json:/opt/keycloak/data/import/quarkus-realm.json:Z
      - ./keystores/keycloak-keystore.jks:/etc/keycloak-keystore.jks:Z
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:8080/auth/realms/kogito-marco"]
    #  #test: ["CMD", "curl", "-f", "http://localhost:8080/auth/realms/kogito"]
    #  interval: 2s
    #  timeout: 1s
    #  # Marco: Modified 'retries' from 50 to 500
    #  retries: 500
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: kogito-user
      KC_DB_PASSWORD: kogito-pass
      KC_DB_SCHEMA: public

    command:
      - start
      - --import-realm
      - --hostname-strict=false 
      - --https-key-store-file=/etc/keycloak-keystore.jks